### ISSUE TITLE
Install Plugin 

### ISSUE THREAD

**Issue by ShadowAbsorber** [Manebot/manebot#5]
Hi, I created a docker stack using your instructions. I can't install any plugins. Please, help. I need to connect docker to internet?

[2020-02-29 21:04:28.261] [Thread-10] [27/root Thread-10] [INFO] root -> plugin install ts3
root -> Problem executing command: ☛ Plugin not found, or no versions are available.

[2020-02-29 21:22:16.215] [Thread-11] [30/root Thread-11] [INFO] root -> plugin install discord
root -> Problem executing command: ☛ Plugin not found, or no versions are available.
21/root console>

**Comment by ShadowAbsorber** [comment]
Can look at problem???

**Comment by Manevolent** [comment]
Yes, Internet access is required to download plugins.  However, the infrastructure behind plug-in delivery on my end, which served up plugins until recently, is no longer servicing these artifacts under the currently hard-coded domain.

At some point in the future, I may move to hosting plugins officially on Maven central or something similar.  Until then, unfortunately Manebot plugins are not available for download unless they are manually compiled and deployed to your own Maven repository.

**Comment by ShadowAbsorber** [comment]
Many thank you for replys! When I use maven to compile it fail and I see "teamlixo.net" in console and 404 error. I am new to maven and will post output of new error quick for you to see.

**Comment by Manevolent** [comment]
The same applies in this case; for any compilation errors relating to that domain, those affected libraries must be compiled and deployed to a custom Maven repository, for example such as the manebot-core project.

**Comment by Manevolent** [comment]
Closing this, as I do not have any current plans to swap things over on this project for the near term.

**Comment by ShadowAbsorber** [comment]
Many thanks
