### ISSUE TITLE
shit project stay away

### ISSUE THREAD

**Issue by ShadowAbsorber** [Manebot/manebot#6]
projects are not intodate. dev does not help or give alternative

**Comment by Manevolent** [comment]
Hi 22.  Take your butthurt elsewhere

**Comment by ShadowAbsorber** [comment]
Oh wow. You actually talked to me directly. I guess you're not a complete pussy after all.

**Comment by Manevolent** [comment]
Nope.  Take care.

**Comment by ShadowAbsorber** [comment]
Still waiting for the apology

**Comment by Manevolent** [comment]
No you're not.  You know I didn't block your number; antics like this are just embarrassing on your part.  I mean, if you're mad you're mad, I can't fix that bro.  I'm just not feeding your ego at this point 🤷
